# src/main/resources/application-dev.yml

server:
  port: 8082 # 服务器上通常用 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 支持环境变量注入，方便 Docker 部署
    url: "jdbc:mysql://${DB_HOST:10.33.9.41}:${DB_PORT:3306}/${DB_NAME:lab_platform_dev}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    username: ${DB_USER:root}
    password: ${DB_PASS:zZ15903750100.}

  flyway:
    enabled: false

  data:
    # redis 配置
    redis:
      # 地址
      host: ${REDIS_HOST}
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms


mybatis-plus:
  configuration:
    # ✅ Dev 环境也开启 SQL 打印，方便前端联调时排查问题
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

usr:
  env: "dev"

lab:
  jwt:
    # 随便写一串乱码，但在生产环境要保密且足够长
    secret: ${LAB_JWT_SECRET:LocalDevSecretKeyOnlyForDebuggingDO_NOT_USE_IN_PROD}
    expiration: 30 #  (单位分钟)
    token-header: Authorization
    token-prefix: "Bearer "