spring:
  application:
    name: lab-plarform
  flyway:
    locations: classpath:db/migration
    clean-disabled: true
    baseline-on-migrate: true
  profiles:
    active: local

# Knife4j
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hengyu.lab # ????????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# --- MyBatis-Plus  ---
mybatis-plus:
  map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-enums-package: com.hengyu.**.domain.**.constant
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id

# application.yml
lab:
  jwt:
    # 随便写一串乱码，但在生产环境要保密且足够长
    secret: ${LAB_JWT_SECRET}
    expiration: 30 #  (单位分钟)
    token-header: Authorization
    token-prefix: "Bearer "