CREATE TABLE if not exists t_feedback
(
    id          BIGINT       NOT NULL COMMENT '主键',
    title       VARCHAR(255) NOT NULL COMMENT '标题',
    content     TEXT COMMENT '内容',
    status      INT      DEFAULT 0 COMMENT '状态',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     INT      DEFAULT 0,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS sys_user
(
    id            BIGINT       NOT NULL COMMENT '主键',
    username      VARCHAR(128) NOT NULL COMMENT '用户名',
    password      VARCHAR(255) NOT NULL COMMENT '密码',
    real_name     VARCHAR(128) NOT NULL COMMENT '真实姓名',
    email         VARCHAR(128) NOT NULL COMMENT '邮箱',
    mobile        VARCHAR(128) NOT NULL COMMENT '手机号',
    identity_type INT      DEFAULT 1 COMMENT '业务身份',
    create_time   DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted       INT      DEFAULT 0,
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_mobile UNIQUE (mobile),
    CONSTRAINT uk_email UNIQUE (email),
    PRIMARY KEY (id)
);



-- ----------------------------
-- 1、角色信息表
-- ----------------------------
DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role
(
    role_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name           VARCHAR(30)  NOT NULL,
    role_key            VARCHAR(100) NOT NULL,
    role_sort           INT          NOT NULL,
    data_scope          CHAR(1) DEFAULT '1',
    status              CHAR(1)      NOT NULL,
    deleted             CHAR(1) DEFAULT '0',
    menu_check_strictly TINYINT DEFAULT 1,
    create_time         TIMESTAMP,
    update_time         TIMESTAMP,
    PRIMARY KEY (role_id)
);

-- 在 H2 中，建议显式指定列名插入，或者确保值顺序完全匹配
INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, deleted,
                      menu_check_strictly, create_time, update_time)
VALUES (1, '超级管理员', 'admin', 1, '1', '0', '0', 1, CURRENT_TIMESTAMP, NULL);

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, deleted,
                      menu_check_strictly, create_time, update_time)
VALUES (2, '普通角色', 'common', 2, '2', '0', '0', 1, CURRENT_TIMESTAMP, NULL);


-- ----------------------------
-- 2、菜单权限表
-- ----------------------------
DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu
(
    menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    menu_name   VARCHAR(50) NOT NULL,
    parent_id   BIGINT       DEFAULT 0,
    order_num   INT          DEFAULT 0,
    path        VARCHAR(200) DEFAULT '',
    component   VARCHAR(255) DEFAULT NULL,
    query       VARCHAR(255) DEFAULT NULL,
    route_name  VARCHAR(50)  DEFAULT '',
    is_frame    INT          DEFAULT 1,
    is_cache    INT          DEFAULT 0,
    menu_type   CHAR(1)      DEFAULT '',
    visible     CHAR(1)      DEFAULT '0',
    status      CHAR(1)      DEFAULT '0',
    perms       VARCHAR(100) DEFAULT NULL,
    icon        VARCHAR(100) DEFAULT '#',
    create_by   VARCHAR(64)  DEFAULT '',
    create_time TIMESTAMP,
    update_by   VARCHAR(64)  DEFAULT '',
    update_time TIMESTAMP,
    remark      VARCHAR(500) DEFAULT '',
    PRIMARY KEY (menu_id)
);

insert into sys_menu
values ('1', '系统管理', '0', '1', 'system', null, '', '', 1, 0, 'M', '0', '0', '', 'system',
        'admin', now(), '', null, '系统管理目录');
insert into sys_menu
values ('2', '系统监控', '0', '2', 'monitor', null, '', '', 1, 0, 'M', '0', '0', '', 'monitor',
        'admin', now(), '', null, '系统监控目录');
insert into sys_menu
values ('3', '系统工具', '0', '3', 'tool', null, '', '', 1, 0, 'M', '0', '0', '', 'tool', 'admin',
        now(), '', null, '系统工具目录');
insert into sys_menu
values ('4', '若依官网', '0', '4', 'http://ruoyi.vip', null, '', '', 0, 0, 'M', '0', '0', '',
        'guide', 'admin', now(), '', null, '若依官网地址');

insert into sys_menu
values ('100', '用户管理', '1', '1', 'user', 'system/user/index', '', '', 1, 0, 'C', '0', '0',
        'system:user:list', 'user', 'admin', now(), '', null, '用户管理菜单');
insert into sys_menu
values ('101', '角色管理', '1', '2', 'role', 'system/role/index', '', '', 1, 0, 'C', '0', '0',
        'system:role:list', 'peoples', 'admin', now(), '', null, '角色管理菜单');


-- ----------------------------
-- 3、用户和角色关联表
-- ----------------------------
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);


-- ----------------------------
-- 4、角色和菜单关联表
-- ----------------------------
DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu
(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
insert into sys_role_menu
values ('2', '1');
insert into sys_role_menu
values ('2', '2');
insert into sys_role_menu
values ('2', '3');
insert into sys_role_menu
values ('2', '4');
insert into sys_role_menu
values ('2', '100');
insert into sys_role_menu
values ('2', '101');


-- 1. 成果主表
DROP TABLE IF EXISTS sys_outcome;

CREATE TABLE sys_outcome
(
    `id`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `title`       VARCHAR(512) NOT NULL COMMENT '成果标题',

    `type`        VARCHAR(32)  NOT NULL COMMENT '成果类型',
    `status`      VARCHAR(32)  NOT NULL COMMENT '状态',

    `create_by`   VARCHAR(64)  DEFAULT '' COMMENT '创建者',
    `update_by`   VARCHAR(64)  DEFAULT '' COMMENT '更新者',
    `create_time` TIMESTAMP    DEFAULT NULL COMMENT '创建时间', -- H2 推荐用 TIMESTAMP
    `update_time` TIMESTAMP    DEFAULT NULL COMMENT '更新时间',
    `deleted`     INT          DEFAULT 0,
    `remark`      VARCHAR(500) DEFAULT NULL COMMENT '备注',

    PRIMARY KEY (`id`)
);

-- H2 需要单独创建索引
CREATE INDEX idx_sys_outcome_type ON sys_outcome (`type`);
CREATE INDEX idx_sys_outcome_create_by ON sys_outcome (`create_by`);


-- 2. 成果作者关联表
DROP TABLE IF EXISTS sys_outcome_author;

CREATE TABLE sys_outcome_author
(
    `id`               BIGINT      NOT NULL AUTO_INCREMENT COMMENT '主键',
    `outcome_id`       BIGINT      NOT NULL COMMENT '关联成果ID',

    `user_id`          BIGINT               DEFAULT NULL COMMENT '系统用户ID',
    `author_name`      VARCHAR(64) NOT NULL COMMENT '作者姓名',

    `sort`             INT         NOT NULL DEFAULT 1 COMMENT '作者排名',
    `is_corresponding` TINYINT     NOT NULL DEFAULT 0 COMMENT '是否通讯作者', -- H2 也可以用 BOOLEAN

    PRIMARY KEY (`id`)
);

-- H2 需要单独创建索引
CREATE INDEX idx_sys_outcome_author_outcome_id ON sys_outcome_author (`outcome_id`);


DROP TABLE IF EXISTS sys_outcome_paper;

CREATE TABLE sys_outcome_paper
(
    -- H2 不使用 (20) 这种宽度定义，直接用 BIGINT
    `outcome_id`   BIGINT NOT NULL COMMENT '成果ID (关联 sys_outcome.id)',

    `journal_name` VARCHAR(255) DEFAULT NULL COMMENT '期刊名称',
    `issn`         VARCHAR(32)  DEFAULT NULL COMMENT 'ISSN号',

    -- H2 推荐使用 TIMESTAMP 来对应 Java 的 LocalDateTime
    `publish_time` TIMESTAMP    DEFAULT NULL COMMENT '发表时间',

    PRIMARY KEY (`outcome_id`)
);
