CREATE TABLE if not exists t_feedback
(
    id          BIGINT       NOT NULL COMMENT '主键',
    title       VARCHAR(255) NOT NULL COMMENT '标题',
    content     TEXT COMMENT '内容',
    status      INT      DEFAULT 0 COMMENT '状态',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     INT      DEFAULT 0,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS sys_user
(
    id            BIGINT       NOT NULL COMMENT '主键',
    username      VARCHAR(128) NOT NULL COMMENT '用户名',
    password      VARCHAR(255) NOT NULL COMMENT '密码',
    real_name     VARCHAR(128) NOT NULL COMMENT '真实姓名',
    email         VARCHAR(128) NOT NULL COMMENT '邮箱',
    mobile        VARCHAR(128) NOT NULL COMMENT '手机号',
    identity_type INT      DEFAULT 1 COMMENT '业务身份',
    create_time   DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted       INT      DEFAULT 0,
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_mobile UNIQUE (mobile),
    CONSTRAINT uk_email UNIQUE (email),
    PRIMARY KEY (id)
);



-- ----------------------------
-- 1、角色信息表
-- ----------------------------
DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role
(
    role_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name           VARCHAR(30)  NOT NULL,
    role_key            VARCHAR(100) NOT NULL,
    role_sort           INT          NOT NULL,
    data_scope          CHAR(1) DEFAULT '1',
    status              CHAR(1)      NOT NULL,
    deleted             CHAR(1) DEFAULT '0',
    menu_check_strictly TINYINT DEFAULT 1,
    create_time         TIMESTAMP,
    update_time         TIMESTAMP,
    PRIMARY KEY (role_id)
);

-- 在 H2 中，建议显式指定列名插入，或者确保值顺序完全匹配
INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, deleted,
                      menu_check_strictly, create_time, update_time)
VALUES (1, '超级管理员', 'admin', 1, '1', '0', '0', 1, CURRENT_TIMESTAMP, NULL);

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, deleted,
                      menu_check_strictly, create_time, update_time)
VALUES (2, '普通角色', 'common', 2, '2', '0', '0', 1, CURRENT_TIMESTAMP, NULL);


-- ----------------------------
-- 2、菜单权限表
-- ----------------------------
DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu
(
    menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    menu_name   VARCHAR(50) NOT NULL,
    parent_id   BIGINT       DEFAULT 0,
    order_num   INT          DEFAULT 0,
    path        VARCHAR(200) DEFAULT '',
    component   VARCHAR(255) DEFAULT NULL,
    query       VARCHAR(255) DEFAULT NULL,
    route_name  VARCHAR(50)  DEFAULT '',
    is_frame    INT          DEFAULT 1,
    is_cache    INT          DEFAULT 0,
    menu_type   CHAR(1)      DEFAULT '',
    visible     CHAR(1)      DEFAULT '0',
    status      CHAR(1)      DEFAULT '0',
    perms       VARCHAR(100) DEFAULT NULL,
    icon        VARCHAR(100) DEFAULT '#',
    create_by   VARCHAR(64)  DEFAULT '',
    create_time TIMESTAMP,
    update_by   VARCHAR(64)  DEFAULT '',
    update_time TIMESTAMP,
    remark      VARCHAR(500) DEFAULT '',
    PRIMARY KEY (menu_id)
);


-- ----------------------------
-- 3、用户和角色关联表
-- ----------------------------
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);


-- ----------------------------
-- 4、角色和菜单关联表
-- ----------------------------
DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu
(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
